---
apiVersion: v1
kind: Service
metadata:
  name: kasonjim-test-service
  labels:
    username: kasonjim
    env: test
spec:
  type: ClusterIP
  selector:
    app: kasonjim-test-redis
  ports:
  - name: helloflask
    port: 6379
    targetPort: 6379
