---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kasonjim-test-data
  labels:
    username: kasonjim
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
