---
apiVersion: v1
kind: Service
metadata:
  name: kasonjim-test-flask-service
  labels:
    username: kasonjim
    env: test
spec:
  type: ClusterIP
  selector:
    app: kasonjim-test-flask
  ports:
  - name: helloflask
    port: 5000
    targetPort: 5000
